name: zen_colposcope
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  awesome_bottom_bar: ^1.2.2
  device_preview: ^1.1.0
  sqflite: ^2.2.8+4
  flutter_screenutil: ^5.7.0
  flutter_native_splash: ^2.2.19
  cupertino_icons: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo-bordered.png
